version: '3.8'

services:
  backend:
    volumes:
      - "./:/app"
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - tgwui
      - super__redis
      - super__postgres
    networks:
      - super_network
    
  celery:
    volumes:
      - "./:/app"
    build:
      context: .
      dockerfile: DockerfileCelery
    depends_on:
      - tgwui
      - super__redis
      - super__postgres
    networks:
      - super_network
    
  gui:
    build: ./gui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8001
    networks:
      - super_network
    volumes:
      - ./gui:/app
      - /app/node_modules
      - /app/.next

  tgwui:
    build:
      context: .
      target: llama-cublas  # Specify the variant to build
      dockerfile: DockerfileTGWUI
      args:
        - LCL_SRC_DIR=text-generation-webui  # Developers - see Dockerfile app_base
    container_name: text-generation-webui
    environment:
      - EXTRA_LAUNCH_ARGS="--chat --listen --verbose --extensions openai" # Custom launch args (e.g., --model MODEL_NAME)
    ports:
      - 7860:7860  # Default web port
      - 5000:5000  # Default API port
      - 5005:5005  # Default streaming port
      - 5001:5001  # Default OpenAI API extension port
    volumes:
      - ./tgwui_config/loras:/app/loras
      - ./tgwui_config/models:/app/models
      - ./tgwui_config/presets:/app/presets
      - ./tgwui_config/prompts:/app/prompts
      - ./tgwui_config/softprompts:/app/softprompts
      - ./tgwui_config/training:/app/training
    logging:
      driver:  json-file
      options:
        max-file: "3"   # number of files or file count
        max-size: '10m'
    networks:
      - super_network
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0,1']
                capabilities: [gpu]


  super__redis:
    image: "redis:latest"
    networks:
      - super_network

  super__postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=superagi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=super_agi_main
    volumes:
      - superagi_postgres_data:/var/lib/postgresql/data/
    networks:
      - super_network
    ports:
      - "5432:5432"

networks:
  super_network:
    driver: bridge

volumes:
  superagi_postgres_data:
